DROP TABLE IF EXISTS Player_In_Game;
DROP TABLE IF EXISTS Historial_Movements;
DROP TABLE IF EXISTS Historial;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Partida;
DROP TABLE IF EXISTS GameConfiguration;
DROP TABLE IF EXISTS Usuari;
